version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
      - SQL_ENGINE=django.db.backends.sqlite3
      - SQL_DATABASE=db.sqlite3
      - SQL_USER=user
      - SQL_PASSWORD=password
      - SQL_HOST=db
      - SQL_PORT=5432
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
